// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmiHealth.Persistence.Data;

#nullable disable

namespace UmiHealth.Persistence.Migrations
{
    [DbContext(typeof(SharedDbContext))]
    partial class SharedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UmiHealth.Domain.Entities.PaymentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_type");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<string>("PaymentReceipt")
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("payment_receipt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_date");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("character varying(255)")
                        .HasColumnName("approved_by");

                    b.Property<string>("TransactionId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<string>("ConfirmationNumber")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmation_number");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("character varying(500)")
                        .HasColumnName("additional_notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.HasKey("id")
                        .HasName("pk_payment_records");

                    b.HasIndex("branch_id")
                        .HasDatabaseName("ix_payment_records_branch_id");

                    b.HasIndex("deleted_at")
                        .HasDatabaseName("ix_payment_records_deleted_at");

                    b.HasIndex("tenant_id")
                        .HasDatabaseName("ix_payment_records_tenant_id");

                    b.HasIndex("updated_at")
                        .HasDatabaseName("ix_payment_records_updated_at");

                    b.ToTable("payment_records", "shared");
                });
#pragma warning restore 612, 618
        }
    }
}
